name: avaliacao_04
description: Aplicações de banco de dados com SQLite3 em Dart.
version: 1.0.0
repository: https://github.com/OE17/pdm2-242

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  http: ^0.13.6
  path: ^1.8.0
  flutter:
    sdk: flutter 
  sqflite: ^2.0.0+3  
  sqlite3: ^1.11.2
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
