name: avaliacao_04
description: Um programa Dart que usa a biblioteca Mailer para enviar email para o Gmail.
repository: https://github.com/OE17/pdm2-242
version: 1.0.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  path: ^1.8.0
  mailer: ^5.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.21.0
